# Generated by Django 5.2.3 on 2025-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGenres',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'genre_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPlatforms',
            fields=[
                ('pk', models.CompositePrimaryKey('product_id', 'platform_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_platforms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_tags', models.TextField(blank=True, null=True)),
                ('screenshot_urls', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('screenshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'screenshots',
                'managed': False,
            },
        ),
    ]
